config/routes.rb
Rails.application.routes.draw do
  resources :active_hours, path: 'aktivitet' do
  end
  get '/indstillinger/aktivitet', to: 'active_hours#index'
  get '/indstillinger/aktivitet/ny', to: 'active_hours#new'
  post '/indstillinger/aktivitet/ny', to: 'active_hours#create'
  resources :companies
  resources :tutors_documents
  resources :documents
  resources :reviews
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tutors_categories
  resources :products
  get 'rooms/show'
  resources :sub_categories
  resources :categories, path: 'kategorier'
  get '/kategorier2', to: 'categories#index2'
  get '/home', to: 'pages#home'
  get '/contact1', to: 'pages#contact1'
  get '/contact2', to: 'pages#contact2'
  get '/veiledere', to: 'pages#veiledere'
  get '/mobil', to: 'pages#mobil'
  get '/mobil2', to: 'pages#mobil2'
  root to: 'pages#landing_page'
  devise_for :accounts, path: 'accounts', controllers: { sessions: "accounts/sessions", registrations: "accounts/registrations", confirmations: "accounts/confirmations", passwords: "accounts/passwords", unlocks: "accounts/unlocks" }
  resources :accounts, path: 'konto'
  devise_scope :account do
    get '/konto-logg-inn', to: "accounts/sessions#new"
    get '/konto-logg-inn', to: "accounts/sessions#new"
  end

  mount ActionCable.server => '/cable'

  devise_for :tutors, path: 'tutors', controllers: { tutors: "tutors", sessions: "tutors/sessions", registrations: "tutors/registrations", confirmations: "tutors/confirmations", passwords: "tutors/passwords", unlocks: "tutors/unlocks" }

  resources :tutors, path: 'raadgiver' do
    get '/book', to: 'bookings#new'
    post '/book', to: 'bookings#create'
  end
  devise_scope :tutor do
#    get '/:id/book', to: 'bookings#new'
#    post '/:id/book', to: 'bookings#create'

    get  '/logg-in',       to: 'tutors/sessions#new'
    post '/logg-in',       to: 'tutors/sessions#create'
    get  '/veileder/ny',   to: 'tutors/registrations#new'
    post '/veileder/ny',   to: 'tutors/registrations#create'
    get '/raadgiver-logg-inn', to: 'tutors/sessions#new'
    get '/indstillinger/:id/rediger', to: 'tutors/registrations#edit', as: :rediger
    post '/indstillinger/:id/rediger', to: 'tutors/registrations#update'
    #get  '/raadgiver/:id', to: 'tutors#show', as: :raadgiver
  end

  get 'kontrakt', to: 'pages#contract'
  get 'download-kontrakt', to: 'pages#download_contract'
  get '/ring', to: 'pages#ring'
  
  resources :tutors do
    resources :reviews
  end
  get '/indstillinger', to: 'settings#index'
  get '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  put '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  get '/tak-vent', to: 'pages#thank_you_pending'
  get '/tak', to: 'pages#thank_you'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all
  get "home/download_pdf"

  post :approve_tutors, to: "tutors#tutors_pending_approval", as: :approve_tutors

end

app/models/document.rb
class Document < ApplicationRecord
	has_one :tutor
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file, :tutor_id)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file %>
    <%= form.text_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.file %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <strong>File:</strong>
  <%= @document.file %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>