config/routes.rb
Rails.application.routes.draw do
  resources :active_hours, path: 'aktivitet' do
  end
  get '/indstillinger/aktivitet', to: 'active_hours#index'
  get '/indstillinger/aktivitet/ny', to: 'active_hours#new'
  post '/indstillinger/aktivitet/ny', to: 'active_hours#create'
  resources :companies
  resources :tutors_documents
  resources :documents
  resources :reviews
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tutors_categories
  resources :products
  get 'rooms/show'
  resources :sub_categories
  resources :categories, path: 'kategorier'
  get '/kategorier2', to: 'categories#index2'
  get '/home', to: 'pages#home'
  get '/contact1', to: 'pages#contact1'
  get '/contact2', to: 'pages#contact2'
  get '/veiledere', to: 'pages#veiledere'
  get '/mobil', to: 'pages#mobil'
  get '/mobil2', to: 'pages#mobil2'
  root to: 'pages#landing_page'
  devise_for :accounts, path: 'accounts', controllers: { sessions: "accounts/sessions", registrations: "accounts/registrations", confirmations: "accounts/confirmations", passwords: "accounts/passwords", unlocks: "accounts/unlocks" }
  resources :accounts, path: 'konto'
  devise_scope :account do
    get '/konto-logg-inn', to: "accounts/sessions#new"
    get '/konto-logg-inn', to: "accounts/sessions#new"
  end

  mount ActionCable.server => '/cable'

  devise_for :tutors, path: 'tutors', controllers: { tutors: "tutors", sessions: "tutors/sessions", registrations: "tutors/registrations", confirmations: "tutors/confirmations", passwords: "tutors/passwords", unlocks: "tutors/unlocks" }

  resources :tutors, path: 'raadgiver' do
    get '/book', to: 'bookings#new'
    post '/book', to: 'bookings#create'
  end
  devise_scope :tutor do
#    get '/:id/book', to: 'bookings#new'
#    post '/:id/book', to: 'bookings#create'

    get  '/logg-in',       to: 'tutors/sessions#new'
    post '/logg-in',       to: 'tutors/sessions#create'
    get  '/veileder/ny',   to: 'tutors/registrations#new'
    post '/veileder/ny',   to: 'tutors/registrations#create'
    get '/raadgiver-logg-inn', to: 'tutors/sessions#new'
    get '/indstillinger/:id/rediger', to: 'tutors/registrations#edit', as: :rediger
    post '/indstillinger/:id/rediger', to: 'tutors/registrations#update'
    #get  '/raadgiver/:id', to: 'tutors#show', as: :raadgiver
  end

  get 'kontrakt', to: 'pages#contract'
  get 'download-kontrakt', to: 'pages#download_contract'
  get '/ring', to: 'pages#ring'
  
  resources :tutors do
    resources :reviews
  end
  get '/indstillinger', to: 'settings#index'
  get '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  put '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  get '/tak-vent', to: 'pages#thank_you_pending'
  get '/tak', to: 'pages#thank_you'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all
  get "home/download_pdf"

  post :approve_tutors, to: "tutors#tutors_pending_approval", as: :approve_tutors

end

app/models/active_hour.rb
class ActiveHour < ApplicationRecord
	has_one :tutor

	def active_time
		start.strftime('%a %d.%m.%Y') + ' - ' + self.end.strftime('%a %d.%m.%Y')
	end

end

app/controllers/active_hours_controller.rb
class ActiveHoursController < ApplicationController
  before_action :set_active_hour, only: [:show, :edit, :update, :destroy]

  # GET /active_hours
  # GET /active_hours.json
  def index
    @active_hours = ActiveHour.where(tutor_id: current_tutor.id).order('start DESC')
    #@active_hours.each do |ah|
    #  if ah.start.future?
    #    @activity_future = ActiveHour.where(tutor_id: current_tutor.id).order('start ASC')
    #  elsif 
    #    @activity_past = ActiveHour.where(tutor_id: current_tutor.id).order('start ASC')
    #  end
    #end
  end

  # GET /active_hours/1
  # GET /active_hours/1.json
  def show
  end

  # GET /active_hours/new
  def new
    @active_hour = ActiveHour.new
  end

  # GET /active_hours/1/edit
  def edit
  end

  # POST /active_hours
  # POST /active_hours.json
  def create
    @active_hour = ActiveHour.new(active_hour_params)

    respond_to do |format|
      if @active_hour.save
        format.html { redirect_to indstillinger_aktivitet_path, notice: 'Aktivitet ble lagret.' }
        format.json { render :show, status: :created, location: indstillinger_aktivitet_path }
      else
        format.html { render :new }
        format.json { render json: @active_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /active_hours/1
  # PATCH/PUT /active_hours/1.json
  def update
    respond_to do |format|
      if @active_hour.update(active_hour_params)
        format.html { redirect_to indstillinger_aktivitet_path, notice: 'Aktivitet ble oppdatteret.' }
        format.json { render :show, status: :ok, location: indstillinger_aktivitet_path }
      else
        format.html { render :edit }
        format.json { render json: @active_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /active_hours/1
  # DELETE /active_hours/1.json
  def destroy
    @active_hour.destroy
    respond_to do |format|
      format.html { redirect_to indstillinger_aktivitet_path, notice: 'Aktivitet ble slettet.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_hour
      @active_hour = ActiveHour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_hour_params
      params.require(:active_hour).permit(:start, :end, :tutor_id)
    end
end

app/helpers/active_hours_helper.rb
module ActiveHoursHelper
end

app/views/active_hours/_form.html.erb
<%= form_with(model: active_hour, local: true) do |form| %>
  <% if active_hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(active_hour.errors.count, "error") %> prohibited this active_hour from being saved:</h2>

      <ul>
      <% active_hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div><br>

  <%= form.hidden_field :tutor_id, value: current_tutor.id %>

  <div class="actions">
    <%= form.submit 'Opprett aktivitet', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/active_hours/_new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_active_hour').modal('show');

app/views/active_hours/create.js.erb
$('.calendar').fullCalendar(
  'renderActiveHour', 
  $.parseJSON("<%=j render(@active_hour, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/active_hours/destroy.js.erb
$('.calendar').fullCalendar('removeActiveHours', [<%= @active_hour.id %>])
$('.modal').modal('hide');

app/views/active_hours/edit.html.erb
<h1>Editing active Hour</h1>

<%= render 'form', active_hour: @active_hour %>

<%= link_to 'Show', @active_hour %> |
<%= link_to 'Back', active_hours_path %>

app/views/active_hours/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_active_hour').modal('show');

app/views/active_hours/index.html.erb
<%= render('/settings/nav_settings') %>

<div class="active-hours">
  <%= link_to 'Legg til aktive timer', indstillinger_aktivitet_ny_path, class: 'approve-button', style: 'float: right;' %>
  <h2>Aktivitet</h2>
  <br>
  <table class="table">
    <tbody>
      <% @active_hours.each do |active_hour| %>
        <% if active_hour.start.future? %>
          <tr style="cursor: pointer;">
            <td onclick="myFunction('active_hour<%= active_hour.id %>');"><%= active_hour.active_time %></td>
          </tr>
        <% elsif %>
          <tr style="background: #f3f2f2;">
            <td><%= active_hour.active_time %></td>
          </tr>
        <% end %>
        <tr class="togglable-tr" id="active_hour<%= active_hour.id %>" style="display: none;border-left:4px solid #009C4D;background: #f7f7f7">
          <td colspan="3">
            <%= form_for active_hour do |f| %>

            <div class="row">
              <div class="col-md-8 col-sm-8">

                <div class="field">
                  <%= f.label :start %>
                  <%= f.datetime_select :start %>
                </div>

                <div class="field">
                  <%= f.label :slut %>
                  <%= f.datetime_select :end %>
                </div>
              </div>
              <div class="col-md-2 col-sm-2">

                <%= f.submit 'Oppdatter', class: 'btn btn-default' %>
              </div>
              <div class="col-md-2 col-sm-2">
                <%= link_to active_hour_path(active_hour), method: :delete, data: { confirm: "Er du sikker?" } do %>
                  <span><i class="fa fa-trash" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </div>

            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/active_hours/index.js.erb
json.array! @active_hours do |active_hour|
  date_format = active_hour.all_day_active_hour? ? '%Y-%m-%d' : '%Y-%m-%dT%H:%M:%S'
  json.id active_hour.id
  json.title active_hour.title
  json.start active_hour.start.strftime(date_format)
  json.end active_hour.end.strftime(date_format)
  json.color active_hour.color unless active_hour.color.blank?
  json.allDay active_hour.all_day_active_hour? ? true : false
  json.update_url active_hour_path(active_hour, method: :patch)
  json.edit_url edit_active_hour_path(active_hour)
end

app/views/active_hours/new.html.erb
<%= render('/settings/nav_settings') %>

<h1>Legg til aktive timer</h1>
<br>
<%= render 'form', active_hour: @active_hour %>

app/views/active_hours/show.html.erb
<p>
  <strong>From:</strong>
  <%= @active_hour.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @active_hour.to %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @active_hour.tutor_id %>
</p>

<%= link_to 'Edit', edit_active_hour_path(@active_hour) %> |
<%= link_to 'Back', active_hours_path %>

app/views/active_hours/update.js.erb
$('.calendar').fullCalendar('removeActiveHours', [<%= @active_hour.id %>]);
$('.calendar').fullCalendar(
  'renderActiveHour', 
  $.parseJSON("<%=j render(@active_hour, format: :json).html_safe %>"), 
  true
);
$('.modal').modal('hide');