config/routes.rb
Rails.application.routes.draw do
  resources :active_hours, path: 'aktivitet' do
  end
  get '/indstillinger/aktivitet', to: 'active_hours#index'
  get '/indstillinger/aktivitet/ny', to: 'active_hours#new'
  post '/indstillinger/aktivitet/ny', to: 'active_hours#create'
  resources :companies
  resources :tutors_documents
  resources :documents
  resources :reviews
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :tutors_categories
  resources :products
  get 'rooms/show'
  resources :sub_categories
  resources :categories, path: 'kategorier'
  get '/kategorier2', to: 'categories#index2'
  get '/home', to: 'pages#home'
  get '/contact1', to: 'pages#contact1'
  get '/contact2', to: 'pages#contact2'
  get '/veiledere', to: 'pages#veiledere'
  get '/mobil', to: 'pages#mobil'
  get '/mobil2', to: 'pages#mobil2'
  root to: 'pages#landing_page'
  devise_for :accounts, path: 'accounts', controllers: { sessions: "accounts/sessions", registrations: "accounts/registrations", confirmations: "accounts/confirmations", passwords: "accounts/passwords", unlocks: "accounts/unlocks" }
  resources :accounts, path: 'konto'
  devise_scope :account do
    get '/konto-logg-inn', to: "accounts/sessions#new"
    get '/konto-logg-inn', to: "accounts/sessions#new"
  end

  mount ActionCable.server => '/cable'

  devise_for :tutors, path: 'tutors', controllers: { tutors: "tutors", sessions: "tutors/sessions", registrations: "tutors/registrations", confirmations: "tutors/confirmations", passwords: "tutors/passwords", unlocks: "tutors/unlocks" }

  resources :tutors, path: 'raadgiver' do
    get '/book', to: 'bookings#new'
    post '/book', to: 'bookings#create'
  end
  devise_scope :tutor do
#    get '/:id/book', to: 'bookings#new'
#    post '/:id/book', to: 'bookings#create'

    get  '/logg-in',       to: 'tutors/sessions#new'
    post '/logg-in',       to: 'tutors/sessions#create'
    get  '/veileder/ny',   to: 'tutors/registrations#new'
    post '/veileder/ny',   to: 'tutors/registrations#create'
    get '/raadgiver-logg-inn', to: 'tutors/sessions#new'
    get '/indstillinger/:id/rediger', to: 'tutors/registrations#edit', as: :rediger
    post '/indstillinger/:id/rediger', to: 'tutors/registrations#update'
    #get  '/raadgiver/:id', to: 'tutors#show', as: :raadgiver
  end

  get 'kontrakt', to: 'pages#contract'
  get 'download-kontrakt', to: 'pages#download_contract'
  get '/ring', to: 'pages#ring'
  
  resources :tutors do
    resources :reviews
  end
  get '/indstillinger', to: 'settings#index'
  get '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  put '/venter-pa-godkjenning', to: 'tutors#tutors_pending_approval'
  get '/tak-vent', to: 'pages#thank_you_pending'
  get '/tak', to: 'pages#thank_you'

  get "/404", :to => "errors#not_found", :via => :all
  get "/500", :to => "errors#internal_server_error", :via => :all
  get "home/download_pdf"

  post :approve_tutors, to: "tutors#tutors_pending_approval", as: :approve_tutors

end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
	has_many :sub_categories
	has_many :tutors_categories
	has_many :tutors, -> { distinct }, through: :tutors_categories
  friendly_id :name, use: :slugged

	scope :min_rating, -> (rating) { joins(:reviews).group("tutors.id").having('AVG(reviews.rating) > ?', rating) if rating }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index

    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      #@tutors_categories = TutorsCategory.where(category_id: @category)
      @tutors = @category.tutors.approved.page(params[:page])
      #@tutors = Tutor.approved.where(id: @tutors_categories).page(params[:page])
      @categories = Category.all.order('name ASC')
    else
      #@categories = Category.all.left_joins(:tutors)
                      #.group(:id)
                      #.order('COUNT(tutors.id) DESC')
      @categories = Category.all.order('name ASC')
      @tutors = Tutor.approved.page(params[:page])
    end

    if params.has_key?(:sub_category)
      @sub_category = SubCategory.find_by_name(params[:sub_category])
      @tutors_categories = TutorsCategory.where(sub_category_id: @sub_category)
    end
    #@online_tutors = Tutor.where('approved = ? AND online = ?', true, true)
    #@sub_categories = SubCategory.joins(:tutor).group("sub_categories.tutor_id").order("count(sub_categories.tutor_id) desc")
    #@sub_categories = SubCategory.left_joins(:tutors)
    #                  .group(:id)
    #                  .order('COUNT(tutors.id) DESC')
  end
  def index2

    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      #@tutors_categories = TutorsCategory.where(category_id: @category)
      @tutors = @category.tutors.approved.page(params[:page])
      #@tutors = Tutor.approved.where(id: @tutors_categories).page(params[:page])
      @categories = Category.all.order('name ASC')
    else
      #@categories = Category.all.left_joins(:tutors)
                      #.group(:id)
                      #.order('COUNT(tutors.id) DESC')
      @categories = Category.all.order('name ASC')
      @tutors = Tutor.approved.page(params[:page])
    end

    if params.has_key?(:sub_category)
      @sub_category = SubCategory.find_by_name(params[:sub_category])
      @tutors_categories = TutorsCategory.where(sub_category_id: @sub_category)
    end
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :sub_category_id, :category_id, :first_name, :last_name, :current_password, :description, :phone, :email, :anonymous, :gdpr, :approved)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_show.html.erb
<div id="display_category_id">
<%= @category %>fff
<%= @category.name %>

</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="desktop">
  <div class="row">

    <div class="col-md-3 col-sm-3 categories-list-container">
      <div class="categories-list">
        <div class="list-2">
          <input placeholder="Søkeboks" style="background: none; border: 1px solid #b5e2e6; color: #1c1c1c; width: 100%; padding: 10px;">
          <% @categories.each do |cat| %>
            <%= link_to categories_path(category: cat.name) do %>
              <div class="list-category">
                <%= cat.name %>
                <span class="count"><%= cat.tutors.approved.count %></span>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="categories-results">

      <div class="col-md-9 col-sm-9 search-results">
        <%# if @sub_categories.try(:any?) %>
          <%# @sub_categories.each do |sub_cat| %>
            <%#= link_to sub_cat.name, sub_categories_path(sub_category: sub_cat.name) %>
          <%# end %>
        <%# end %>
        <% if params[:category].present? %><h2><%= @category.name %></h2><% end %><br>

          <% @tutors.each do |tutor| %>

            <%= link_to tutor_path(tutor), target: :blank do %>
              <div class="search-results-single">
                <div class="row">
                  <div class="col-md-3 col-sm-3">

                    <% if tutor.anonymous %>
                      <%= image_tag('/anonymous.jpg') %>
                    <% else %>
                      <% if tutor.profile_picture? %>
                        <%= image_tag tutor.profile_picture.url(:profile_picture) %>
                      <% else %>
                        <%= image_tag('/default.png') %>
                      <% end %>
                    <% end %>     
                  </div>
                  <div class="col-md-9 col-sm-9">
                    <div class="row">
                      <div class="col-md-8 col-sm-8">

                        <div style="display: inline-flex;">

                          <h2><%= tutor.full_name %></h2>

                          <% if tutor.online? %>
                            <div class="bubble">
                              <span class="bubble-outer-dot">
                                <span class="bubble-inner-dot"></span>
                              </span>
                            </div>
                          <% end %>

                        </div><br>

                        <div style="display: inline-flex;" class="average-review-rating" data-score="<% if tutor.reviews.blank? %>0<% else %><%= tutor..reviews.average(:rating).round(2) %><% end %>"></div><br>
                        
                        <% if tutor.reviews.any? %>
                          <span class="text-muted" style="font-size: 12px;">
                            (<%= tutor.reviews.count %>)
                          </span>
                        <% end %>

                        <p><%= truncate(tutor.description, length: 150) %> <%= 'Les mere' if tutor.description? && tutor.description.length > 150 %></p>
                      </div>

                      <div class="col-md-4 col-sm-4">
                        <div class="tutor-card-footer">
                          <div class="first">
                            <div class="inner">
                              <% tutor.sub_categories.limit(6).each do |sub_cat| %>
                                <span class="tag"><%= sub_cat.name %></span> 
                              <% end %>
                            </div>
                          </div>
                          <div class="inner">
                            <strong>Online igen:</strong>
                            <span class="online-again">
                              <% tutor.active_hours.where(tutor_id: tutor.id).limit(1).each do |hour| %>
                                <% if hour.start.future? %>
                                  <%= hour.start.strftime('%b %M %Y') %>
                                <% end %>
                              <% end %>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
        <% end %>
        <%= paginate @tutors %>
      </div>
    </div>
  </div>
</div>


<div class="card" style="display: none;">
  <div class="card-body">
      <center><h4 class="card-title">Kategorier</h4></center>
      <!-- Nav tabs -->
      <div class="vtabs">
        <ul class="nav nav-tabs tabs-vertical" role="tablist">
          <% @categories.each do |cat| %>
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#<%= cat.id %>" role="tab">
                <span class="hidden-sm-up">
                  <i class="ti-home"></i>
                </span>
                <span class="hidden-xs-down">
                  <%= cat.name %>
                </span>
              </a>
            </li>
          <% end %>
        </ul>

        <div class="tab-content">
          <% @categories.each do |cat| %>
            <div class="tab-pane active" id="<%= cat.id %>" role="tabpanel">
              <% SubCategory.where(category_id: cat.id).each do |sub_cat| %>
                <h3><%= link_to sub_cat.name, sub_category_path(sub_cat) %></h3>
              <% end %>
            </div>
          <% end %>
        </div>




      </div>
  </div>
</div>



<div class="mobile">
  <div class="row">
    <div class="categories-list">
      <div class="list-2">
        <input placeholder="Søkeboks" style="background: none; border: 1px solid #b5e2e6; color: #1c1c1c; width: 100%; padding: 10px;">
        <% @categories.each do |cat| %>
          <%= link_to categories_path(category: cat.name) do %>
            <div class="list-category">
              <%= cat.name %>
              <span class="count"><%= cat.tutors.approved.count %></span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="categories-results">

      <%# if @sub_categories.try(:any?) %>
        <%# @sub_categories.each do |sub_cat| %>
          <%#= link_to sub_cat.name, sub_categories_path(sub_category: sub_cat.name) %>
        <%# end %>
      <%# end %>
      <% if params[:category].present? %><h2><%= @category.name %></h2><% end %><br>

        <% @tutors.each do |tutor| %>

          <%= link_to tutor_path(tutor), target: :blank do %>
            <div class="search-results-single">
              <div class="row">
                <div class="col-md-3 col-sm-3">

                  <% if tutor.anonymous %>
                    <%= image_tag('/anonymous.jpg') %>
                  <% else %>
                    <% if tutor.profile_picture? %>
                      <%= image_tag tutor.profile_picture.url(:profile_picture) %>
                    <% else %>
                      <%= image_tag('/default.png') %>
                    <% end %>
                  <% end %>     
                </div>
                <div class="col-md-9 col-sm-9">
                  <div class="row">
                    <div class="col-md-8 col-sm-8">

                      <div style="display: inline-flex;">

                        <h2><%= tutor.full_name %></h2>

                        <% if tutor.online? %>
                          <div class="bubble">
                            <span class="bubble-outer-dot">
                              <span class="bubble-inner-dot"></span>
                            </span>
                          </div>
                        <% end %>

                      </div><br>

                      <div style="display: inline-flex;" class="average-review-rating" data-score="<% if tutor.reviews.blank? %>0<% else %><%= tutor..reviews.average(:rating).round(2) %><% end %>"></div><br>
                      
                      <% if tutor.reviews.any? %>
                        <span class="text-muted" style="font-size: 12px;">
                          (<%= tutor.reviews.count %>)
                        </span>
                      <% end %>

                      <p><%= truncate(tutor.description, length: 150) %> <%= 'Les mere' if tutor.description? && tutor.description.length > 150 %></p>
                    </div>

                    <div class="col-md-4 col-sm-4">
                      <div class="tutor-card-footer">
                        <div class="first">
                          <div class="inner">
                            <% tutor.sub_categories.limit(6).each do |sub_cat| %>
                              <span class="tag"><%= sub_cat.name %></span> 
                            <% end %>
                          </div>
                        </div>
                        <div class="inner">
                          <strong>Online igen:</strong>
                          <span class="online-again">
                            <% tutor.active_hours.where(tutor_id: tutor.id).limit(1).each do |hour| %>
                              <% if hour.start.future? %>
                                <%= hour.start.strftime('%b %M %Y') %>
                              <% end %>
                            <% end %>
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
      <% end %>
      <%= paginate @tutors %>
    </div>
  </div>
</div>


<div class="card" style="display: none;">
  <div class="card-body">
      <center><h4 class="card-title">Kategorier</h4></center>
      <!-- Nav tabs -->
      <div class="vtabs">
        <ul class="nav nav-tabs tabs-vertical" role="tablist">
          <% @categories.each do |cat| %>
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#<%= cat.id %>" role="tab">
                <span class="hidden-sm-up">
                  <i class="ti-home"></i>
                </span>
                <span class="hidden-xs-down">
                  <%= cat.name %>
                </span>
              </a>
            </li>
          <% end %>
        </ul>

        <div class="tab-content">
          <% @categories.each do |cat| %>
            <div class="tab-pane active" id="<%= cat.id %>" role="tabpanel">
              <% SubCategory.where(category_id: cat.id).each do |sub_cat| %>
                <h3><%= link_to sub_cat.name, sub_category_path(sub_cat) %></h3>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/categories/index2.html.erb
<div style="font-family: poppins !important">
<% @categories.each do |cat| %>
  <%= link_to categories_path(category: cat.name) do %>
      <%= cat.name %>
  <% end %>
<% end %>

<% if params[:category].present? %><h2><%= @category.name %></h2><% end %><br>

<div class="row">
  <% @tutors.each do |tutor| %>
    <div class="col-md-3 col-sm-4">
      <div class="tutor-listing">
        <%= link_to tutor_path(tutor), target: :blank do %>

          <% if tutor.anonymous %>
            <%= image_tag('/anonymous.jpg') %>
          <% else %>
            <% if tutor.profile_picture? %>
              <%= image_tag tutor.profile_picture.url(:profile_picture) %>
            <% else %>
              <%= image_tag('/default.png') %>
            <% end %>
          <% end %>

          <div class="tutor-listing-inner">

            <div style="float: right">

              <div style="display: inline-flex;" class="average-review-rating" data-score="
                <% if tutor.reviews.blank? %>0<% else %><%= tutor..reviews.average(:rating).round(2) %><% end %>">
                
              </div><br>
              
              <span class="text-muted" style="float:right;">
                <%= tutor.reviews.count %> omtaler
              </span>
            </div>

            <h2><%= tutor.full_name %></h2>

            <% if tutor.online? %>
              <div class="bubble">
                <span class="bubble-outer-dot">
                  <span class="bubble-inner-dot"></span>
                </span>
              </div>
            <% end %>

            <div class="tags">
              <% tutor.sub_categories.limit(3).each do |sub_cat| %>
                <span class="tag"><%= sub_cat.name %></span> 
              <% end %>
            </div>

            <span class="online-again">Online igen:</span>
            <% tutor.active_hours.where(tutor_id: tutor.id).limit(1).each do |hour| %>
              <% if hour.start.future? %>
                <%= hour.start.strftime('%b %M %Y') %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="all_categories_container">
  <div class="categories_header_text"><%= @category.name %></div>

		<span class="row all_categories container">
		    <div style="overflow: auto;height: 450px;padding: 10px;">
		        <% @sub_categories.each do |cat| %>
		            <%= link_to sub_category_path(cat) do %>
		              <div class="col-md-6 col-sm-6 col-xs-6">
		                    <div class="sub_category_mobile"">
		                        <i class="fa fa-user-o" aria-hidden="true"></i><br>
		                        <span class="cat-title"> <%= cat.name %></span>
		                    </div>
		                </div>
		            <% end %>
		        <% end %>
		    </div>
		</span>
</div>